### PR TITLE
Add different brew paths documentation

### PR DESCRIPTION
**Pull request by B0go**
I had a few issues regarding finding the right location to point to the `auto.fish` and `chruby.fish` until I found out that homebrew uses different base paths for Intel and Apple based machines: https://docs.brew.sh/FAQ#why-should-i-install-homebrew-in-the-default-location

Added a new line to the documentation to help others in the future :)

### CODE REVIEW

**Comment by B0go** [comment]
cc @JeanMertz

**Comment by ioquatix** [comment]
@B0go can you please confirm this is still accurate and rebase, we will merge it. Thanks!

**Comment by B0go** [comment]
@ioquatix yes this is still relevant!
I just updated my branch with master's most recent commits :)

**Comment by ioquatix** [comment]
Great, thanks!

**Pull request merged**
